# Generated by Django 2.0.5 on 2018-06-05 20:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180605_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(height_field=30, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateField(default=datetime.datetime(2018, 6, 5, 20, 29, 3, 663828, tzinfo=utc)),
        ),
    ]
