# Generated by Django 2.0.5 on 2018-06-05 20:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180605_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateField(default=datetime.datetime(2018, 6, 5, 20, 33, 54, 745498, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(height_field=30, null=True, upload_to='media'),
        ),
    ]
