# Generated by Django 2.0.5 on 2018-06-05 20:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180605_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateField(default=datetime.datetime(2018, 6, 5, 20, 41, 37, 180204, tzinfo=utc)),
        ),
    ]
